# Generated by Django 5.1.2 on 2025-04-23 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_alter_appointment_doctor_alter_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_houers', models.JSONField(default=list, help_text="['12:00:00 - 13:30:00', '13:30:00 - 15:00:00', '15:00:00 - 16:30:00', '16:30:00 - 18:00:00', '18:00:00 - 19:30:00', '19:30:00 - 21:00:00', '21:00:00 - 22:30:00', '22:30:00 - 24:00:00']")),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
