# Generated by Django 5.1.2 on 2025-04-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0006_availabilityslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='available_houers',
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='docotr_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
