# Generated by Django 5.1.2 on 2025-04-25 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0007_remove_availabilityslot_available_houers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slot', to=settings.AUTH_USER_MODEL),
        ),
    ]
