# Generated by Django 5.1.2 on 2025-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0008_alter_availabilityslot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
