# Generated by Django 5.1.2 on 2025-04-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0009_customuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
    ]
