# Generated by Django 5.1.2 on 2025-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0010_delete_availabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
